[package]
name = "buf_file"
version = "0.2.9"
authors = ["Josh Karns <jkarns275@gmail.com>"]
description = "A Buffered File that allows for both reading and writing"
license = "MIT"

[dependencies]
lru-cache = "0.1"

[dev-dependencies]
rand = "0.3"
tempfile = "2.1"
seek_bufread = "1.2.0"
